// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/dark/proto/demo.proto

package com.lw.proto;

public interface FileBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile();

  /**
   * <code>string fileName = 2;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int32 opt = 6;</code>
   */
  int getOpt();

  /**
   * <code>bytes fileLength = 15;</code>
   */
  com.google.protobuf.ByteString getFileLength();
}
