// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/dark/proto/demo.proto

package com.lw.proto;

/**
 * <pre>
 *第二个类的名称为FileDeal，我将它用作操作FileBean类。但是在这里不需要对两个类做关联性操作。属性包含如下所示
 * </pre>
 *
 * Protobuf type {@code FileDeal}
 */
public  final class FileDeal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileDeal)
    FileDealOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileDeal.newBuilder() to construct.
  private FileDeal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileDeal() {
    dealType_ = com.google.protobuf.ByteString.EMPTY;
    dealResult_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileDeal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            dealType_ = input.readBytes();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dealResult_ = s;
            break;
          }
          case 74: {
            com.lw.proto.FileBean.Builder subBuilder = null;
            if (bean_ != null) {
              subBuilder = bean_.toBuilder();
            }
            bean_ = input.readMessage(com.lw.proto.FileBean.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bean_);
              bean_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lw.proto.Demo.internal_static_FileDeal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lw.proto.Demo.internal_static_FileDeal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lw.proto.FileDeal.class, com.lw.proto.FileDeal.Builder.class);
  }

  public static final int DEALTYPE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString dealType_;
  /**
   * <code>bytes dealType = 1;</code>
   */
  public com.google.protobuf.ByteString getDealType() {
    return dealType_;
  }

  public static final int DEALRESULT_FIELD_NUMBER = 5;
  private volatile java.lang.Object dealResult_;
  /**
   * <code>string dealResult = 5;</code>
   */
  public java.lang.String getDealResult() {
    java.lang.Object ref = dealResult_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dealResult_ = s;
      return s;
    }
  }
  /**
   * <code>string dealResult = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDealResultBytes() {
    java.lang.Object ref = dealResult_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dealResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BEAN_FIELD_NUMBER = 9;
  private com.lw.proto.FileBean bean_;
  /**
   * <code>.FileBean bean = 9;</code>
   */
  public boolean hasBean() {
    return bean_ != null;
  }
  /**
   * <code>.FileBean bean = 9;</code>
   */
  public com.lw.proto.FileBean getBean() {
    return bean_ == null ? com.lw.proto.FileBean.getDefaultInstance() : bean_;
  }
  /**
   * <code>.FileBean bean = 9;</code>
   */
  public com.lw.proto.FileBeanOrBuilder getBeanOrBuilder() {
    return getBean();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!dealType_.isEmpty()) {
      output.writeBytes(1, dealType_);
    }
    if (!getDealResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dealResult_);
    }
    if (bean_ != null) {
      output.writeMessage(9, getBean());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!dealType_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, dealType_);
    }
    if (!getDealResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dealResult_);
    }
    if (bean_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getBean());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lw.proto.FileDeal)) {
      return super.equals(obj);
    }
    com.lw.proto.FileDeal other = (com.lw.proto.FileDeal) obj;

    if (!getDealType()
        .equals(other.getDealType())) return false;
    if (!getDealResult()
        .equals(other.getDealResult())) return false;
    if (hasBean() != other.hasBean()) return false;
    if (hasBean()) {
      if (!getBean()
          .equals(other.getBean())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEALTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDealType().hashCode();
    hash = (37 * hash) + DEALRESULT_FIELD_NUMBER;
    hash = (53 * hash) + getDealResult().hashCode();
    if (hasBean()) {
      hash = (37 * hash) + BEAN_FIELD_NUMBER;
      hash = (53 * hash) + getBean().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lw.proto.FileDeal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lw.proto.FileDeal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lw.proto.FileDeal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lw.proto.FileDeal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lw.proto.FileDeal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lw.proto.FileDeal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lw.proto.FileDeal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lw.proto.FileDeal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lw.proto.FileDeal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lw.proto.FileDeal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lw.proto.FileDeal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lw.proto.FileDeal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lw.proto.FileDeal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *第二个类的名称为FileDeal，我将它用作操作FileBean类。但是在这里不需要对两个类做关联性操作。属性包含如下所示
   * </pre>
   *
   * Protobuf type {@code FileDeal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileDeal)
      com.lw.proto.FileDealOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lw.proto.Demo.internal_static_FileDeal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lw.proto.Demo.internal_static_FileDeal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lw.proto.FileDeal.class, com.lw.proto.FileDeal.Builder.class);
    }

    // Construct using com.lw.proto.FileDeal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dealType_ = com.google.protobuf.ByteString.EMPTY;

      dealResult_ = "";

      if (beanBuilder_ == null) {
        bean_ = null;
      } else {
        bean_ = null;
        beanBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lw.proto.Demo.internal_static_FileDeal_descriptor;
    }

    public com.lw.proto.FileDeal getDefaultInstanceForType() {
      return com.lw.proto.FileDeal.getDefaultInstance();
    }

    public com.lw.proto.FileDeal build() {
      com.lw.proto.FileDeal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lw.proto.FileDeal buildPartial() {
      com.lw.proto.FileDeal result = new com.lw.proto.FileDeal(this);
      result.dealType_ = dealType_;
      result.dealResult_ = dealResult_;
      if (beanBuilder_ == null) {
        result.bean_ = bean_;
      } else {
        result.bean_ = beanBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lw.proto.FileDeal) {
        return mergeFrom((com.lw.proto.FileDeal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lw.proto.FileDeal other) {
      if (other == com.lw.proto.FileDeal.getDefaultInstance()) return this;
      if (other.getDealType() != com.google.protobuf.ByteString.EMPTY) {
        setDealType(other.getDealType());
      }
      if (!other.getDealResult().isEmpty()) {
        dealResult_ = other.dealResult_;
        onChanged();
      }
      if (other.hasBean()) {
        mergeBean(other.getBean());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lw.proto.FileDeal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lw.proto.FileDeal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString dealType_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes dealType = 1;</code>
     */
    public com.google.protobuf.ByteString getDealType() {
      return dealType_;
    }
    /**
     * <code>bytes dealType = 1;</code>
     */
    public Builder setDealType(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dealType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes dealType = 1;</code>
     */
    public Builder clearDealType() {
      
      dealType_ = getDefaultInstance().getDealType();
      onChanged();
      return this;
    }

    private java.lang.Object dealResult_ = "";
    /**
     * <code>string dealResult = 5;</code>
     */
    public java.lang.String getDealResult() {
      java.lang.Object ref = dealResult_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dealResult_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dealResult = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDealResultBytes() {
      java.lang.Object ref = dealResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dealResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dealResult = 5;</code>
     */
    public Builder setDealResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dealResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dealResult = 5;</code>
     */
    public Builder clearDealResult() {
      
      dealResult_ = getDefaultInstance().getDealResult();
      onChanged();
      return this;
    }
    /**
     * <code>string dealResult = 5;</code>
     */
    public Builder setDealResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dealResult_ = value;
      onChanged();
      return this;
    }

    private com.lw.proto.FileBean bean_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lw.proto.FileBean, com.lw.proto.FileBean.Builder, com.lw.proto.FileBeanOrBuilder> beanBuilder_;
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public boolean hasBean() {
      return beanBuilder_ != null || bean_ != null;
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public com.lw.proto.FileBean getBean() {
      if (beanBuilder_ == null) {
        return bean_ == null ? com.lw.proto.FileBean.getDefaultInstance() : bean_;
      } else {
        return beanBuilder_.getMessage();
      }
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public Builder setBean(com.lw.proto.FileBean value) {
      if (beanBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bean_ = value;
        onChanged();
      } else {
        beanBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public Builder setBean(
        com.lw.proto.FileBean.Builder builderForValue) {
      if (beanBuilder_ == null) {
        bean_ = builderForValue.build();
        onChanged();
      } else {
        beanBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public Builder mergeBean(com.lw.proto.FileBean value) {
      if (beanBuilder_ == null) {
        if (bean_ != null) {
          bean_ =
            com.lw.proto.FileBean.newBuilder(bean_).mergeFrom(value).buildPartial();
        } else {
          bean_ = value;
        }
        onChanged();
      } else {
        beanBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public Builder clearBean() {
      if (beanBuilder_ == null) {
        bean_ = null;
        onChanged();
      } else {
        bean_ = null;
        beanBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public com.lw.proto.FileBean.Builder getBeanBuilder() {
      
      onChanged();
      return getBeanFieldBuilder().getBuilder();
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    public com.lw.proto.FileBeanOrBuilder getBeanOrBuilder() {
      if (beanBuilder_ != null) {
        return beanBuilder_.getMessageOrBuilder();
      } else {
        return bean_ == null ?
            com.lw.proto.FileBean.getDefaultInstance() : bean_;
      }
    }
    /**
     * <code>.FileBean bean = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lw.proto.FileBean, com.lw.proto.FileBean.Builder, com.lw.proto.FileBeanOrBuilder> 
        getBeanFieldBuilder() {
      if (beanBuilder_ == null) {
        beanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lw.proto.FileBean, com.lw.proto.FileBean.Builder, com.lw.proto.FileBeanOrBuilder>(
                getBean(),
                getParentForChildren(),
                isClean());
        bean_ = null;
      }
      return beanBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileDeal)
  }

  // @@protoc_insertion_point(class_scope:FileDeal)
  private static final com.lw.proto.FileDeal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lw.proto.FileDeal();
  }

  public static com.lw.proto.FileDeal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileDeal>
      PARSER = new com.google.protobuf.AbstractParser<FileDeal>() {
    public FileDeal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileDeal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileDeal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileDeal> getParserForType() {
    return PARSER;
  }

  public com.lw.proto.FileDeal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

