// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/dark/proto/demo.proto

package com.lw.proto;

public interface FileDealOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileDeal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes dealType = 1;</code>
   */
  com.google.protobuf.ByteString getDealType();

  /**
   * <code>string dealResult = 5;</code>
   */
  java.lang.String getDealResult();
  /**
   * <code>string dealResult = 5;</code>
   */
  com.google.protobuf.ByteString
      getDealResultBytes();

  /**
   * <code>.FileBean bean = 9;</code>
   */
  boolean hasBean();
  /**
   * <code>.FileBean bean = 9;</code>
   */
  com.lw.proto.FileBean getBean();
  /**
   * <code>.FileBean bean = 9;</code>
   */
  com.lw.proto.FileBeanOrBuilder getBeanOrBuilder();
}
