// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/dark/proto/product.proto

package org.dark.beans;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface productDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:productData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string proId = 2;</code>
     */
    java.lang.String getProId();
    /**
     * <code>string proId = 2;</code>
     */
    com.google.protobuf.ByteString
        getProIdBytes();

    /**
     * <code>string createTime = 3;</code>
     */
    java.lang.String getCreateTime();
    /**
     * <code>string createTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();

    /**
     * <code>double price = 4;</code>
     */
    double getPrice();

    /**
     * <code>double xPrice = 5;</code>
     */
    double getXPrice();

    /**
     * <code>float discount = 6;</code>
     */
    float getDiscount();

    /**
     * <code>int32 inventory = 7;</code>
     */
    int getInventory();
  }
  /**
   * Protobuf type {@code productData}
   */
  public  static final class productData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:productData)
      productDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use productData.newBuilder() to construct.
    private productData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private productData() {
      proId_ = "";
      createTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private productData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              proId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              createTime_ = s;
              break;
            }
            case 33: {

              price_ = input.readDouble();
              break;
            }
            case 41: {

              xPrice_ = input.readDouble();
              break;
            }
            case 53: {

              discount_ = input.readFloat();
              break;
            }
            case 56: {

              inventory_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dark.beans.Product.internal_static_productData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dark.beans.Product.internal_static_productData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dark.beans.Product.productData.class, org.dark.beans.Product.productData.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PROID_FIELD_NUMBER = 2;
    private volatile java.lang.Object proId_;
    /**
     * <code>string proId = 2;</code>
     */
    public java.lang.String getProId() {
      java.lang.Object ref = proId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proId_ = s;
        return s;
      }
    }
    /**
     * <code>string proId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProIdBytes() {
      java.lang.Object ref = proId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object createTime_;
    /**
     * <code>string createTime = 3;</code>
     */
    public java.lang.String getCreateTime() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <code>string createTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private double price_;
    /**
     * <code>double price = 4;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int XPRICE_FIELD_NUMBER = 5;
    private double xPrice_;
    /**
     * <code>double xPrice = 5;</code>
     */
    public double getXPrice() {
      return xPrice_;
    }

    public static final int DISCOUNT_FIELD_NUMBER = 6;
    private float discount_;
    /**
     * <code>float discount = 6;</code>
     */
    public float getDiscount() {
      return discount_;
    }

    public static final int INVENTORY_FIELD_NUMBER = 7;
    private int inventory_;
    /**
     * <code>int32 inventory = 7;</code>
     */
    public int getInventory() {
      return inventory_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getProIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, proId_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, createTime_);
      }
      if (price_ != 0D) {
        output.writeDouble(4, price_);
      }
      if (xPrice_ != 0D) {
        output.writeDouble(5, xPrice_);
      }
      if (discount_ != 0F) {
        output.writeFloat(6, discount_);
      }
      if (inventory_ != 0) {
        output.writeInt32(7, inventory_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getProIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, proId_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, createTime_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, price_);
      }
      if (xPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, xPrice_);
      }
      if (discount_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, discount_);
      }
      if (inventory_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, inventory_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.dark.beans.Product.productData)) {
        return super.equals(obj);
      }
      org.dark.beans.Product.productData other = (org.dark.beans.Product.productData) obj;

      if (getId()
          != other.getId()) return false;
      if (!getProId()
          .equals(other.getProId())) return false;
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (java.lang.Double.doubleToLongBits(getXPrice())
          != java.lang.Double.doubleToLongBits(
              other.getXPrice())) return false;
      if (java.lang.Float.floatToIntBits(getDiscount())
          != java.lang.Float.floatToIntBits(
              other.getDiscount())) return false;
      if (getInventory()
          != other.getInventory()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PROID_FIELD_NUMBER;
      hash = (53 * hash) + getProId().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + XPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getXPrice()));
      hash = (37 * hash) + DISCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDiscount());
      hash = (37 * hash) + INVENTORY_FIELD_NUMBER;
      hash = (53 * hash) + getInventory();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.dark.beans.Product.productData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dark.beans.Product.productData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dark.beans.Product.productData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dark.beans.Product.productData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dark.beans.Product.productData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dark.beans.Product.productData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dark.beans.Product.productData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.dark.beans.Product.productData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.dark.beans.Product.productData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.dark.beans.Product.productData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.dark.beans.Product.productData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.dark.beans.Product.productData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.dark.beans.Product.productData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code productData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:productData)
        org.dark.beans.Product.productDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.dark.beans.Product.internal_static_productData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.dark.beans.Product.internal_static_productData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.dark.beans.Product.productData.class, org.dark.beans.Product.productData.Builder.class);
      }

      // Construct using org.dark.beans.Product.productData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        proId_ = "";

        createTime_ = "";

        price_ = 0D;

        xPrice_ = 0D;

        discount_ = 0F;

        inventory_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dark.beans.Product.internal_static_productData_descriptor;
      }

      public org.dark.beans.Product.productData getDefaultInstanceForType() {
        return org.dark.beans.Product.productData.getDefaultInstance();
      }

      public org.dark.beans.Product.productData build() {
        org.dark.beans.Product.productData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.dark.beans.Product.productData buildPartial() {
        org.dark.beans.Product.productData result = new org.dark.beans.Product.productData(this);
        result.id_ = id_;
        result.proId_ = proId_;
        result.createTime_ = createTime_;
        result.price_ = price_;
        result.xPrice_ = xPrice_;
        result.discount_ = discount_;
        result.inventory_ = inventory_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dark.beans.Product.productData) {
          return mergeFrom((org.dark.beans.Product.productData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.dark.beans.Product.productData other) {
        if (other == org.dark.beans.Product.productData.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getProId().isEmpty()) {
          proId_ = other.proId_;
          onChanged();
        }
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getXPrice() != 0D) {
          setXPrice(other.getXPrice());
        }
        if (other.getDiscount() != 0F) {
          setDiscount(other.getDiscount());
        }
        if (other.getInventory() != 0) {
          setInventory(other.getInventory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.dark.beans.Product.productData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.dark.beans.Product.productData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object proId_ = "";
      /**
       * <code>string proId = 2;</code>
       */
      public java.lang.String getProId() {
        java.lang.Object ref = proId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string proId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProIdBytes() {
        java.lang.Object ref = proId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string proId = 2;</code>
       */
      public Builder setProId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string proId = 2;</code>
       */
      public Builder clearProId() {
        
        proId_ = getDefaultInstance().getProId();
        onChanged();
        return this;
      }
      /**
       * <code>string proId = 2;</code>
       */
      public Builder setProIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createTime_ = "";
      /**
       * <code>string createTime = 3;</code>
       */
      public java.lang.String getCreateTime() {
        java.lang.Object ref = createTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        java.lang.Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createTime = 3;</code>
       */
      public Builder setCreateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createTime = 3;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string createTime = 3;</code>
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createTime_ = value;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 4;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 4;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 4;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private double xPrice_ ;
      /**
       * <code>double xPrice = 5;</code>
       */
      public double getXPrice() {
        return xPrice_;
      }
      /**
       * <code>double xPrice = 5;</code>
       */
      public Builder setXPrice(double value) {
        
        xPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double xPrice = 5;</code>
       */
      public Builder clearXPrice() {
        
        xPrice_ = 0D;
        onChanged();
        return this;
      }

      private float discount_ ;
      /**
       * <code>float discount = 6;</code>
       */
      public float getDiscount() {
        return discount_;
      }
      /**
       * <code>float discount = 6;</code>
       */
      public Builder setDiscount(float value) {
        
        discount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float discount = 6;</code>
       */
      public Builder clearDiscount() {
        
        discount_ = 0F;
        onChanged();
        return this;
      }

      private int inventory_ ;
      /**
       * <code>int32 inventory = 7;</code>
       */
      public int getInventory() {
        return inventory_;
      }
      /**
       * <code>int32 inventory = 7;</code>
       */
      public Builder setInventory(int value) {
        
        inventory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 inventory = 7;</code>
       */
      public Builder clearInventory() {
        
        inventory_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:productData)
    }

    // @@protoc_insertion_point(class_scope:productData)
    private static final org.dark.beans.Product.productData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.dark.beans.Product.productData();
    }

    public static org.dark.beans.Product.productData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<productData>
        PARSER = new com.google.protobuf.AbstractParser<productData>() {
      public productData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new productData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<productData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<productData> getParserForType() {
      return PARSER;
    }

    public org.dark.beans.Product.productData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_productData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_productData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034org/dark/proto/product.proto\"\200\001\n\013produ" +
      "ctData\022\n\n\002id\030\001 \001(\003\022\r\n\005proId\030\002 \001(\t\022\022\n\ncre" +
      "ateTime\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\022\016\n\006xPrice\030\005" +
      " \001(\001\022\020\n\010discount\030\006 \001(\002\022\021\n\tinventory\030\007 \001(" +
      "\005B\020\n\016org.dark.beansb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_productData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_productData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_productData_descriptor,
        new java.lang.String[] { "Id", "ProId", "CreateTime", "Price", "XPrice", "Discount", "Inventory", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
